Add database
89219339769/java-filmorate pull request #38
Opened 2022-11-09 13:57 UTC by 89219339769

2022-11-10 10:06 UTC, sergeymamonov requested changes

2022-11-10 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Лучше еще добавить обработку рантайм ошибки.

2022-11-10 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ObjectAlreadyExistException.java
> +package ru.yandex.practicum.filmorate.exception;
Проверьте корректность названия пакета и пути к пакету в файлах исключениях.

2022-11-10 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public FilmController(FilmService filmService) {
Зачем писать конструктор руками, если можно воспользоваться аннотацией Lombok? Актуально для многих классов.

2022-11-10 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                String sql = "insert into FILM_GENRE values (?, ?)";
Лучше не делать запросов к БД в цикле, так как это грузит БД. Можно воспользоваться jdbcTemplate.batchUpdate

2022-11-10 10:06 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    email    TEXT NOT NULL,
Для таких относительно коротких по длине полей лучше использовать VARCHAR(размер).

2022-11-10 10:06 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
>      private Film getFilm() {
Можно добавить аннотацию @BeforeEach. И тогда не нужно будет вызывать этот метод в начале каждого теста.

2022-11-10 10:06 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        film.setDescription("123456789012345678901234567890123456789012345678901234567890" +
Так не очень хорошо делать, легко ошибиться, непонятно и не удобно проверять. Проще
"a".repeat(нужное количество раз)

2022-11-11 09:59 UTC, 89219339769 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Добрый день. Не совсем понял рекомендацию, handleObjectNotFoundException выбрасывается во время рантайм, например  "error": "Фильм с id=2 не найден." как еще можно обработать эту ошибку?

2022-11-11 21:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Есть два вида ошибок: обрабатываемые и не обрабатываемые. Обрабатываемые ошибки мы обязаны обрабатывать в коде, это требует компилятор. Не обрабатываемые мы не обязаны обрабатывать. К не обрабатываемым ошибка относится, например, NPE. Поэтому на случай возникновения не обрабатываемой ошибки лучше иметь обработчик, который принимает Throwable. Возвращаемый код @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)

2022-11-11 22:49 UTC, sergeymamonov approved these changes

2022-11-12 06:40 UTC, 89219339769 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    }
Спасибо, теперь понятно

2023-02-16 14:46 UTC, merged